name: Deploy Monitoring Script to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy monitoring.py to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure project folder exists
            mkdir -p /home/ubuntu/EC2-Monitoring

            # Copy monitoring.py content
            cat > /home/ubuntu/EC2-Monitoring/monitoring.py << 'EOF'
$(cat monitoring.py)
EOF

            # Optional: show the file on EC2 to confirm
            ls -l /home/ubuntu/EC2-Monitoring/
