name: Deploy Monitoring Script to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy script to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/EC2-Monitoring
            echo "${{ github.workspace }}/monitoring.py"
            scp -i ~/.ssh/id_rsa monitoring.py ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/EC2-Monitoring/
