name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_key }}
        script: |
          cd /home/ubuntu
          if [ ! -d monitoring ]; then
            git clone https://github.com/VeeraReddyRavuri/EC@-Infrastructure-Monitoring.git monitoring
          else
            cd monitoring
            git pull origin main
          fi
          cd monitoring
          nohup python3 monitoring.py > monitor.log 2>&1 &
